apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: marketplace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: tian11qb/market-frontend:latest
        ports:
        - containerPort: 80
